name = "JWTs"
uuid = "d850fbd6-035d-5a70-a269-1ca2e636ac6c"
keywords = ["julialang", "jwt", "jwt-authentication", "jwkset", "signing"]
license = "MIT"
desc = "JSON Web Tokens (JWT) for Julia"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>", "contributors: https://github.com/JuliaWeb/JWTs.jl/graphs/contributors"]
version = "1.0.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
Downloads = "1"
JSON = "0.20, 0.21, 1"
OpenSSL_jll = "3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
